<?php

Route::get('generate-c-routes', function()
{
	return Site::generateControllerRoutes();
});

// Register the controller routes generated by 'generate-c-route'
foreach (Config::get('c_routes') as $route => $controller)
{
	Route::controller($route, $controller);
}