<?php

Route::get('generate-c-routes', function()
{
	return Site::generateControllerRoutes();
});

// See http://laravel.com/docs/security#password-reminders-and-reset
Route::get('password/remind', function()
{
	$view = View::make('site::auth.reminder');
	if (Session::has('error'))
	{
		$view->message = trans(Session::get('reason'));
	}
	elseif (Session::has('success'))
	{
		$view->message = 'An e-mail with the password reset has been sent.';
	}

	return $view->render();
});

Route::post('password/remind', function()
{
	if (Input::get('email'))
	{
		$credentials = array('email' => Input::get('email'));
		return Password::remind($credentials, function($message, $user)
		{
			$message->subject('Your Password Reminder');
		});
	}
});

Route::get('password/reset/{token}', function($token)
{
	return View::make('site::auth.reset')->with('token', $token);
});

Route::post('password/reset/{token}', function()
{
	$row = DB::table('password_reminders')->where('token', $token)->first();
	if ( ! $row)
		App::abort(404);

    $credentials = array(
        'email' => $row->email,
        'password' => Input::get('password'),
        'password_confirmation' => Input::get('password_confirmation')
    );

    return Password::reset($credentials, function($user, $password)
    {
        $user->password = Hash::make($password);
        $user->save();

        return Redirect::to('/');
    });
});

// Register the controller routes (if any) generated by 'generate-c-route' above
foreach (Config::get('c_routes') as $route => $controller)
{
	Route::controller($route, $controller);
}